<?php

return [
    'AL' => "Albania",
    'AD' => "Andorra",
    'AM' => "Armenia",
    'AT' => "Austria",
    'BE' => "Belarus",
    'BA' => "Bulgaria",
    'BG' => "Belgium",
    'CH' => "Switzerland",
    'CY' => "Cyprus",
    'CZ' => "Czech Republic",
    'DE' => "Germany",
    'DK' => "Denmark",
    'ES' => "Estonia",
    'FI' => "Finland",
    'FR' => "France",
    'GB' => "United Kingdom",
    'GE' => "Georgia",
    'GR' => "Greece",
    'HU' => "Hungary",
    'IE' => "Iceland",
    'IT' => "Italy",
    'LT' => "Lithuania",
    'LU' => "Luxembourg",
    'LV' => "Latvia",
    'MC' => "Monaco",
    'MK' => "Macedonia",
    'MT' => "Malta",
    'NO' => "Norway",
    'NL' => "The Netherlands",
    'PL' => "Poland",
    'PT' => "Portugal",
    'RO' => "Romania",
    'RU' => "Russia",
    'SE' => "Sweden",
    'SI' => "Slovenia",
    'SK' => "Slovakia",
	'SM' => "San marino",
	'TR' => "Turkey",
	'UA' => "Ukraine",
	'VA' => "Vatican City"
];